language: objective-c
osx_image: xcode7
xcode_project: DXLinkedMap/DXLinkedMap.xcodeproj
xcode_scheme: DXLinkedMap

script:
- xctool -project DXLinkedMap/DXLinkedMap.xcodeproj -scheme DXLinkedMap build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
